site_name: UA Capstone Tours

nav:
  - Home: index.md
  - Backend Overview: backend-overview.md
  - Data Model: data-model.md
  - API Reference: api-reference.md
  - Development Guide: development-guide.md
  - Deliverables: deliverables.md
  - Team: team.md

docs_dir: docs
